"""create initial tables

Revision ID: 4a781a09f357
Revises: 
Create Date: 2026-05-05 15:41:00.952718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from encryption_file.encypted_string import EncryptedString


# revision identifiers, used by Alembic.
revision: str = '4a781a09f357'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('token', sa.String(length=512), nullable=False),
                    sa.Column('blacklisted_on', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    op.create_index('idx_blacklisted_token',
                    'blacklisted_tokens', ['token'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('first_name', EncryptedString(), nullable=False),
                    sa.Column('last_name', EncryptedString(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('email', EncryptedString(), nullable=False),
                    sa.Column('email_hash', sa.String(
                        length=64), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('phone_number', sa.String(
                        length=20), nullable=True),
                    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole',
                                              native_enum=False), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('email_verified', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('last_login', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_users_email_hash'),
                    'users', ['email_hash'], unique=True)
    op.create_table('uploads',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('original_filename', EncryptedString(
                        length=255), nullable=False),
                    sa.Column('temp_file_id', sa.String(
                        length=512), nullable=False),
                    sa.Column('cloudinary_public_id', EncryptedString(
                        length=255), nullable=False),
                    sa.Column('cloudinary_file_hash', EncryptedString(
                        length=512), nullable=False),
                    sa.Column('cloudinary_file_url', EncryptedString(
                        length=512), nullable=False),
                    sa.Column('cloudinary_file_resource_type',
                              sa.String(length=50), nullable=False),
                    sa.Column('file_type', sa.Enum('DOCUMENT', 'VIDEO', 'IMAGE',
                                                   'AUDIO', name='filetype'), nullable=False),
                    sa.Column('detected_mime', sa.String(
                        length=100), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_uploads_created_at'),
                    'uploads', ['created_at'], unique=False)
    op.create_table('conversions',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('upload_id', sa.UUID(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED',
                                                'FAILED', name='conversionstatus'), nullable=False),
                    sa.Column('output_format', sa.Enum('PDF', 'DOCX', 'TXT', 'HTML', 'MP4', 'AVI', 'MOV', 'WEBM', 'MKV', 'PNG', 'JPG',
                                                       'JPEG', 'WEBP', 'GIF', 'BMP', 'TIFF', 'ICO', 'MP3', 'WAV', 'OGG', name='outputformat'), nullable=False),
                    sa.Column('result_cloudinary_public_id',
                              EncryptedString(length=255), nullable=True),
                    sa.Column('result_cloudinary_url', EncryptedString(
                        length=255), nullable=False),
                    sa.Column('result_cloudinary_file_hash',
                              EncryptedString(length=512), nullable=False),
                    sa.Column('resource_type', EncryptedString(
                        length=512), nullable=False),
                    sa.Column('celery_task_id', EncryptedString(
                        length=512), nullable=False),
                    sa.Column('error_message', EncryptedString(
                        length=512), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['upload_id'], ['uploads.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('upload_id', 'output_format',
                                        name='uq_upload_output')
                    )
    op.create_index('idx_conversion_user_lookup', 'conversions', [
                    'id', 'upload_id'], unique=False)
    op.create_index(op.f('ix_conversions_deleted_at'),
                    'conversions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversions_upload_id'),
                    'conversions', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversions_upload_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_deleted_at'), table_name='conversions')
    op.drop_index('idx_conversion_user_lookup', table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_uploads_created_at'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_blacklisted_token', table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
